# Generated by Django 4.0.5 on 2022-07-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_monitoring', '0002_damagelevel_vegetationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayMonitoringActAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spray_monitoring_act/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spray_monitoring_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='spray_monitoring.spraymonitoringact')),
            ],
            options={
                'db_table': 'spray_monitoring_act_album',
            },
        ),
    ]
