# Generated by Django 4.0.5 on 2022-07-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_monitoring', '0003_spraymonitoringactalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spraymonitoringact',
            name='sprayer',
        ),
        migrations.AddField(
            model_name='spraymonitoringact',
            name='sprayer',
            field=models.ManyToManyField(related_name='+', to='spray_monitoring.sprayer', verbose_name='Purkagich'),
        ),
    ]
