# Generated by Django 4.0.5 on 2022-07-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_monitoring', '0004_remove_spraymonitoringact_sprayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insecticidesyearlyremainder',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
