# Generated by Django 4.0.5 on 2022-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_monitoring', '0007_insecticidesyearlyremainder_unique_insecticide_yearly_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insecticidesyearlyremainder',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
