# Generated by Django 4.0.5 on 2022-08-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_user_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spray_monitoring', '0010_alter_insecticidesyearlyremainder_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsecticideExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('given_date', models.DateField()),
                ('note', models.CharField(max_length=512)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insecticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insecticide_exchanges', to='spray_monitoring.insecticide')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.region')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.region')),
            ],
            options={
                'db_table': 'insecticide_exchange',
            },
        ),
    ]
