# Generated by Django 4.0.5 on 2022-08-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_user_region'),
        ('spray_monitoring', '0013_remove_spraymonitoringact_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insecticideexchange',
            name='sender_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.region'),
        ),
    ]
