# Generated by Django 4.0.5 on 2022-09-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_monitoring', '0014_alter_insecticideexchange_sender_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayMonitoringEfficiencyAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('given_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spray_monitoring_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_acts', to='spray_monitoring.spraymonitoringact')),
            ],
            options={
                'db_table': 'spray_monitoring_efficiency_act',
            },
        ),
        migrations.CreateModel(
            name='SprayMonitoringEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Ishlovning biologik samaradorligi')),
                ('period_in_hours', models.PositiveSmallIntegerField(verbose_name='Ishlovdan keyin otgan vaqt (soat)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spray_monitoring_efficiency_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiencies', to='spray_monitoring.spraymonitoringefficiencyact')),
            ],
            options={
                'db_table': 'spray_monitoring_efficiency',
            },
        ),
    ]
