# Generated by Django 4.1.2 on 2022-10-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_monitoring', '0015_spraymonitoringefficiencyact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spraymonitoringefficiency',
            name='spray_monitoring_efficiency_act',
        ),
        migrations.AddField(
            model_name='spraymonitoringefficiency',
            name='spray_monitoring_act',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='efficiencies', to='spray_monitoring.spraymonitoringact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spraymonitoringefficiencyact',
            name='given_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spraymonitoringefficiencyact',
            name='spray_monitoring_act',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_act', to='spray_monitoring.spraymonitoringact'),
        ),
    ]
