# Generated by Django 4.0.5 on 2022-06-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='users', to='common.district'),
        ),
    ]
