# Generated by Django 4.0.5 on 2022-09-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_user_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='region',
            name='geometry',
        ),
    ]
