# Generated by Django 4.0.5 on 2022-06-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_behaviour_egghatching_fledging_naturalenemy_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locustage',
            table='locust_age',
        ),
        migrations.AlterModelTable(
            name='locuststage',
            table='locust_stage',
        ),
    ]
