# Generated by Django 4.0.5 on 2022-06-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_locustage_table_alter_locuststage_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyact',
            options={'ordering': ['number'], 'verbose_name': 'Акт Обследования саранчи'},
        ),
    ]
