# Generated by Django 4.0.5 on 2022-06-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_surveyact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locust_appearance_detail_info', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
