# Generated by Django 4.0.5 on 2022-06-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_locustappearancedetailinfo_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
