# Generated by Django 4.0.5 on 2022-07-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_alter_locustappearancedetailinfo_natural_enemies'),
    ]

    operations = [
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='locusts',
            field=models.ManyToManyField(related_name='+', to='survey.locust'),
        ),
    ]
