# Generated by Django 4.0.5 on 2022-07-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_locustappearancedetailinfo_locusts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locustappearancedetailinfo',
            name='locusts',
        ),
    ]
