# Generated by Django 4.0.5 on 2022-07-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_remove_locustappearancedetailinfo_locusts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyalbum',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='survey.survey'),
        ),
    ]
