# Generated by Django 4.0.5 on 2022-07-13 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0016_alter_surveyalbum_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwarmDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=128, unique=True)),
                ('name_en', models.CharField(max_length=128, unique=True)),
                ('name_ru', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Плотность в стае',
                'db_table': 'swarm_density',
                'ordering': ['name_uz'],
            },
        ),
        migrations.RemoveField(
            model_name='locustappearancedetailinfo',
            name='adult_density_from',
        ),
        migrations.RemoveField(
            model_name='locustappearancedetailinfo',
            name='adult_density_to',
        ),
        migrations.RemoveField(
            model_name='locustappearancedetailinfo',
            name='swarm_density',
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_copulating',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urchishi va juftlashishi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_feeding_and_roosting',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oziqlanish va osimliklarda ornashishi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_fledging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.fledging', verbose_name='Qanot chiqarish'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_flying',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uchishi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_laying',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tuxum quyishi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_maturity',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urchishga tayyorligi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='adult_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.locuststage', verbose_name='Rivojlanish bosqichi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='average_number_of_eggs_in_pod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kozachadagi tuxumlar soni(ortacha)'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='behaviour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.behaviour', verbose_name='Hatti-harakati'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='egg_hatching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.egghatching', verbose_name='Tuxumdan chiqishi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='egg_pod_density_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kozacha zichligi(ta/m2) dan'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='egg_pod_density_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kozacha zichligi(ta/m2) gacha'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='egg_pod_detected_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Kozacha joylashgan maydon'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='hopper_age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.locustage', verbose_name='Lichinkalar yoshi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='hopper_age_in_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.locustage', verbose_name='Lichikalar yoshi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='hopper_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.locuststage', verbose_name='Rivojlanish bosqichi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='natural_enemies',
            field=models.ManyToManyField(blank=True, related_name='+', to='survey.naturalenemy', verbose_name='Tabiiy kushandalarning borligi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='swarm_maturity',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urchisga tayyorligi'),
        ),
        migrations.AlterField(
            model_name='locustappearancedetailinfo',
            name='viability_of_eggs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tuxumning hayotchanligi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='agronomist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi guruh rahbarining ismi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='biotope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.biotope', verbose_name='Biotop turi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='damaged_area_in_ha',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tarqalgan maydoni'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='locust_appearance',
            field=models.ManyToManyField(related_name='+', to='survey.locustappearance', verbose_name='Chigirtkaning mavjudligi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyed_area_in_ha',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tekshirilgan maydon(ga)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='temperature',
            field=models.CharField(max_length=8, verbose_name='Havo harorati'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='territory_name',
            field=models.CharField(max_length=256, verbose_name='Hudud yoki fermer xojalik nomi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='vegetation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.vegetation', verbose_name='Osimliklar'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='vegetation_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.vegetationcover', verbose_name='Otlarning qalinligi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='wind',
            field=models.CharField(max_length=8, verbose_name='Shamol'),
        ),
    ]
