# Generated by Django 4.0.5 on 2022-07-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_swarmdensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='area_of_hopper_bands_in_m2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Toda tarqalgan yerning maydoni(m2)'),
        ),
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='hopper_density_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Lichinkalar zichligi(ta/m2) dan'),
        ),
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='hopper_density_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Lichinkalar zichligi(ta/m2) dan'),
        ),
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='max_density_in_hopper_band',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Todadagi lichinkalarning maximal miqdori(ta/m2)'),
        ),
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='min_density_in_hopper_band',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Todadagi lichinkalarning minimal miqdori(ta/m2)'),
        ),
        migrations.AddField(
            model_name='locustappearancedetailinfo',
            name='swarm_density',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.swarmdensity', verbose_name='Todalarning zichligi'),
        ),
    ]
