# Generated by Django 4.0.5 on 2022-07-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_locustappearancedetailinfo_area_of_hopper_bands_in_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyact',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='survey.survey'),
        ),
    ]
