# Generated by Django 4.0.5 on 2022-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_alter_surveyact_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyact',
            name='given_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
