# Generated by Django 4.0.5 on 2022-07-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_alter_surveyact_given_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyalbum',
            name='survey',
            field=models.ForeignKey(default=128, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='survey.survey'),
            preserve_default=False,
        ),
    ]
