# Generated by Django 4.0.5 on 2022-09-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_alter_surveyalbum_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='locusts',
            new_name='locust',
        ),
    ]
